export const OPESER_CLIENT_OPTIONS_TOKEN = "OPESER_CLIENT_OPTIONS_TOKEN"
export const OPESER_CLIENT_TOKEN = "OPESER_CLIENT_TOKEN"
export const OPESER_PLUGIN_CONNECTOR_TOKEN = "OPESER_PLUGIN_CONNECTOR_TOKEN"