export const OPESER_CLIENT_OPTIONS_TOKEN = Symbol(
  "OPESER_CLIENT_OPTIONS_TOKEN",
);
export const OPESER_CLIENT_TOKEN = Symbol("OPESER_CLIENT_TOKEN");
export const OPESER_PLUGIN_CONNECTOR_TOKEN = Symbol(
  "OPESER_PLUGIN_CONNECTOR_TOKEN",
);
